import Head from "next/head";
import { NextPage } from "next";
import { RandomFox } from "@/components/RandomFox";
import { useState } from "react";

type ImageItem = {
    id: string;
    url: string;
};

const Home: NextPage = () => {
    //generate a random function between 1 and 123
    const random = (min: number, max: number): number => {
        return Math.floor(Math.random() * (max - min + 1)) + min;
    };

    //generate id randoms
    const generateId = (): string => {
        return Math.random().toString(36).substr(2, 9);
    };

    const [images, setImages] = useState<Array<ImageItem>>([
        {
            id: generateId(),
            url: `https://randomfox.ca/images/${random(1, 123)}.jpg`,
        },
        {
            id: generateId(),
            url: `https://randomfox.ca/images/${random(1, 123)}.jpg`,
        },
        {
            id: generateId(),
            url: `https://randomfox.ca/images/${random(1, 123)}.jpg`,
        },
        {
            id: generateId(),
            url: `https://randomfox.ca/images/${random(1, 123)}.jpg`,
        },
    ]);

    return (
        <>
            <Head>
                <title>App typescript</title>
                <meta
                    name="description"
                    content="Generated by Next with Typescript"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1 className="text-3xl font-bold underline">Hello world!</h1>
                {images.map(({id, url}) => (
                    <div key={id} className="flex justify-center p-4">
                        <RandomFox image={url} />
                    </div>
                ))}
            </main>
        </>
    );
};

export default Home;
